.TH CLR 6 "24 Feb 2024" "v0.3.1-RED" "Games Manual"

.SH NAME
clr - colourise text with string search

.SH SYNOPSIS
.B clr
[ \fB--f from | -a --after | -r --reset-on\fR ]
\fI<string>\fR \fI<colour>\fR ...

.SH DESCRIPTION
Pipe text through clr and colourise it with simple human-readable syntax.

.SH OPTIONS
.TP
\fB-a, --after\fR
Apply \fI<colour>\fR formatting to text after matching \fI<string>\fR.

.TP
\fB-f, --from\fR
Apply \fI<colour>\fR formatting to text starting from the match of \fI<string>\fR.

.TP
\fB-r, --reset-on\fR
Reset text colour to normal after matching \fI<string>\fR.

.TP
\fB-A, --afterx\fR
Apply \fI<hexcolour>\fR formatting to text after matching \fI<string>\fR.

.TP
\fB-F, --fromx\fR
Apply \fI<hexcolour>\fR formatting to text starting from the match of \fI<string>\fR.

.PP
Note: Combining short options is not supported!

.SH EXAMPLE
.B stat README.md | clr red --after velox green --from users blue --from "+" cyan --after ": " green
.br
.B stat README.md | clr --afterx Access: ff0000

.SH SEE ALSO
.B cat(1), lolcat(6)


.SH BUGS
String search may be janky.

.SH AUTHOR
Velox0 <veloxzerror@gmail.com>
